# API de gestão
api_login_check:
    path: /api/login_check

api_pessoa:
    resource: "@PessoaBundle/Controller/"
    type: rest
    prefix: /api
    
api_curso:
    resource: "@CursoBundle/Controller/"
    type: rest
    prefix: /api
    
api_matricula:
    resource: "@MatriculaBundle/Controller/"
    type: rest
    prefix: /api
    
api_vinculo:
    resource: "@VinculoBundle/Controller/"
    type: rest
    prefix: /api
    
api_calendario:
    resource: "@CalendarioBundle/Controller/"
    type: rest
    prefix: /api
    
api_quadro_horario:
    resource: "@QuadroHorarioBundle/Controller/"
    type: rest
    prefix: /api
    
api_avaliacao:
    resource: "@AvaliacaoBundle/Controller/"
    type: rest
    prefix: /api
    
api_aula:
    resource: "@AulaBundle/Controller/"
    type: rest
    prefix: /api
    
api_vaga:
    resource: "@VagaBundle/Controller/"
    type: rest
    prefix: /api
    
api_auth:
    resource: "@AuthBundle/Controller/"
    type: rest
    prefix: /api
    
api_relatorio:
    resource: "@ReportBundle/Controller/"
    type: annotation
    prefix: /api/report

#API do aluno
api_aluno:
    resource: "@AlunoBundle/Controller/"
    type: annotation
    prefix: /api/alunos

# Integrações
integracao_sig:
    resource: "@IntegracaoSigAlimentarBundle/Controller/"
    type: rest
    prefix: /integracoes
   
# Docs    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc