# API
api_pessoa:
    resource: "@PessoaBundle/Controller/"
    type: rest
    prefix: /api
    
api_curso:
    resource: "@CursoBundle/Controller/"
    type: rest
    prefix: /api
    
api_matricula:
    resource: "@MatriculaBundle/Controller/"
    type: rest
    prefix: /api
    
api_vinculo:
    resource: "@VinculoBundle/Controller/"
    type: rest
    prefix: /api
    
api_calendario:
    resource: "@CalendarioBundle/Controller/"
    type: rest
    prefix: /api
    
api_avaliacao:
    resource: "@AvaliacaoBundle/Controller/"
    type: rest
    prefix: /api
    
api_auth:
    resource: "@AuthBundle/Controller/"
    type: rest
    prefix: /api
    
api_reports:
    resource: "@ReportBundle/Controller/"
    type: annotation
    prefix: /api/report
    
# Docs    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc