services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    AlunoBundle\:
        resource: '../../{Service,Listener}'
       
    AlunoBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']