agrupamentos-turma:
    resource: CursoBundle\Controller\AgrupamentoTurmaController
    type:     rest

cursos:
    resource: CursoBundle\Controller\CursoController
    type:     rest
    
cursos-ofertados:
    resource: CursoBundle\Controller\CursoOfertadoController
    type:     rest
    
modalidades-ensino:
    resource: CursoBundle\Controller\ModalidadeEnsinoController
    type:     rest
    
disciplinas:
    resource: CursoBundle\Controller\DisciplinaController
    type:     rest
    
disciplinas-ofertadas:
    resource: CursoBundle\Controller\DisciplinaOfertadaController
    type:     rest
    
etapas:
    resource: CursoBundle\Controller\EtapaController
    type:     rest
    
modulos:
    resource: CursoBundle\Controller\ModuloController
    type:     rest
    
turmas:
    resource: CursoBundle\Controller\TurmaController
    type:     rest
    
turnos:
    resource: CursoBundle\Controller\TurnoController
    type:     rest

vagas:
    resource: CursoBundle\Controller\VagaController
    type:     rest