services:
    facade.curso.cursos:
      class: CursoBundle\Service\CursoFacade
      arguments: ["@doctrine"]
    
    facade.curso.cursos_ofertados:
      class: CursoBundle\Service\CursoOfertadoFacade
      arguments: ["@doctrine"]
    
    facade.curso.turmas:
      class: CursoBundle\Service\TurmaFacade
      arguments: ["@doctrine"]
      calls:
          - [setVagaFacade, ["@facade.curso.vagas"]]
    
    facade.curso.disciplinas_ofertadas:
      class: CursoBundle\Service\DisciplinaOfertadaFacade
      arguments: ["@doctrine"]

    facade.curso.vagas:
      class: CursoBundle\Service\VagaFacade
      arguments: ["@doctrine"]
      
    facade.curso.solicitacaoVagas:
      class: CursoBundle\Service\SolicitacaoVagaFacade
      arguments: ["@doctrine"]