#parameters:
#    user_provider.class: AuthBundle\Service\UserProvider
#    md5_encoder.class: AuthBundle\Service\MD5Encoder

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    AuthBundle\:
        resource: '../../{Service,Listener}'
       
    AuthBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
          - [setViewHandler, ["@fos_rest.view_handler"]]
    
#    user_provider:
#      class: "%user_provider.class%"
#      arguments: ["@doctrine"]
#      
#    md5_encoder:
#      class: "%md5_encoder.class%"
